import { useMemo } from "react";
import { useLocalSearchParams,useRouter } from "expo-router";
import { ScrollView,Text,View,StyleSheet,Pressable } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { products } from "../../src/data/products";
import { ProductArtwork } from "../../src/components/ProductArtwork";
import { useCart } from "../../src/store/cart";
export default function ProductScreen(){const{id}=useLocalSearchParams<{id:string}>();const router=useRouter();const{add}=useCart();const product=useMemo(()=>products.find(p=>p.id===id),[id]);if(!product)return <SafeAreaView style={s.safe}><View style={s.center}><Text>Product not found.</Text><Pressable onPress={()=>router.back()}><Text>Go back</Text></Pressable></View></SafeAreaView>;return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>← Back</Text></Pressable><ProductArtwork product={product} large/><View style={s.meta}><Text style={s.category}>{product.category}</Text><Text style={s.name}>{product.name}</Text><View style={s.row}><Text style={s.price}>{"$"+product.price}</Text><Text style={s.rating}>{"★ "+product.rating+" · "+product.reviews+" reviews"}</Text></View></View><Text style={s.description}>{product.description}</Text><Text style={s.label}>Available colors</Text><View style={s.colors}>{product.colors.map(c=><View key={c} style={[s.color,{backgroundColor:c}]}/>)}</View><View style={s.specs}>{[["SHIPPING","Free over $100"],["RETURNS","30 days"],["STOCK","Ready to ship"]].map(([a,b])=><View key={a}><Text style={s.specLabel}>{a}</Text><Text style={s.specValue}>{b}</Text></View>)}</View><Pressable onPress={()=>{add(product);router.push("/cart")}} style={s.cta}><Text style={s.ctaText}>{"Add to cart · $"+product.price}</Text></Pressable></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F7F7F2"},content:{padding:22,paddingBottom:40},back:{height:42,justifyContent:"center"},backText:{fontSize:13,fontWeight:"700"},meta:{paddingTop:22},category:{fontSize:11,fontWeight:"700",color:"#7D7D75"},name:{fontSize:34,fontWeight:"800",marginTop:5},row:{flexDirection:"row",justifyContent:"space-between",marginTop:10},price:{fontSize:22,fontWeight:"800"},rating:{fontSize:12,color:"#74746D"},description:{fontSize:15,lineHeight:23,color:"#5F5F58",marginTop:22},label:{fontSize:11,fontWeight:"800",marginTop:28},colors:{flexDirection:"row",gap:10,marginTop:12},color:{width:34,height:34,borderRadius:17,borderWidth:1,borderColor:"#D0D0C8"},specs:{marginTop:30,paddingVertical:18,borderTopWidth:1,borderBottomWidth:1,borderColor:"#DFDFD7",flexDirection:"row",justifyContent:"space-between"},specLabel:{fontSize:8,fontWeight:"800",color:"#898980"},specValue:{fontSize:11,fontWeight:"700",marginTop:5},cta:{height:56,borderRadius:20,backgroundColor:"#111",alignItems:"center",justifyContent:"center",marginTop:28},ctaText:{color:"#D8FF5C",fontSize:14,fontWeight:"800"},center:{flex:1,alignItems:"center",justifyContent:"center"}});
